# Generated by Django 4.1.2 on 2022-10-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='tourist_attraction',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
