# Generated by Django 4.1.2 on 2023-03-15 12:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0006_remove_photo_latituderef_remove_photo_longituderef"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="thumbnails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.ImageField(
                    blank=True, null=True, upload_to="shop/images/"
                ),
                default=[],
                size=None,
                verbose_name="photo_thumbnails",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="photo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
