# Generated by Django 4.1.2 on 2023-03-15 12:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_photo_thumbnails_photo_user_usertier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="thumbnails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.ImageField(
                    blank=True, null=True, upload_to="shop/images/"
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="photo_thumbnails",
            ),
        ),
    ]
