# Generated by Django 4.1.2 on 2023-03-15 13:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_photo_thumbnails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="thumbnails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=256, null=True),
                blank=True,
                null=True,
                size=None,
                verbose_name="photo_thumbnails",
            ),
        ),
    ]
