# Generated by Django 4.1.2 on 2023-03-15 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_photo_thumbnails"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoThumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thumbnail_size", models.IntegerField()),
                ("thumbnail", models.ImageField(upload_to="shop/images//thumbnails")),
                (
                    "photo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.photo"
                    ),
                ),
            ],
        ),
    ]
