# Generated by Django 4.1.2 on 2023-03-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_photothumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photothumbnail",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="shop/images/"),
        ),
    ]
