# Generated by Django 4.1.2 on 2023-03-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_photothumbnail_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
