# Generated by Django 4.1.2 on 2023-03-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_photo_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PhotoThumbnail",
            new_name="Thumbnail",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="thumbnails",
        ),
    ]
