# Generated by Django 4.1.2 on 2022-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='country',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='latitude',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='latituderef',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='longitude',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='longituderef',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
