# Generated by Django 4.1.2 on 2022-10-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_photo_country_alter_photo_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='shop/images/'),
        ),
    ]
