# Generated by Django 4.1.2 on 2023-02-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_photo_city_photo_tourist_attraction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="latituderef",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="longituderef",
        ),
    ]
